Change names for TriangularViewCL stuff
bstatcomp/math pull request #14
Opened 2019-07-24 13:38 UTC by SteveBronder

## Summary

This branch mostly changes bstatcomp:matrix_cl_triangularity so that instead of `TriangularViewCL` we have `PartialViewCL`. 

I changed the `combine` and `commonNonzeroPart` we do for `+` and `*` because it feels like they make more sense.

## Tests

New tests added for the partial matrix types

## Checklist

- [x] Copyright holder: Steve Bronder

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

2019-07-24 16:42 UTC, rok-cesnovar requested changes
1 comment and 1 thing where we just need to pick one and roll with it.

2019-07-24 16:42 UTC, rok-cesnovar commented on stan/math/opencl/add.hpp
> +                                     A.triangular_view() + B.triangular_view());
Should we also change triangular_view() to partial_view()?

2019-07-24 16:42 UTC, rok-cesnovar commented on stan/math/opencl/partial_types.hpp
> + * Performs bitwise @c and to deduce return type from adding two @c matrix_cls
Should we stick with \c? Dont have an opinion here really.

2019-07-24 21:03 UTC, SteveBronder commented
I agree with both the above will make those changes tmrw.

@t4c1 cool with you?

2019-07-25 05:29 UTC, rok-cesnovar commented
I think Tadej is on vacation till next week, but I think he should be fine it. The name change is great, we can discuss on the main PR if he agrees with replacing combine.

2019-07-25 07:07 UTC, SteveBronder commented on stan/math/opencl/partial_types.hpp
> + * Performs bitwise @c and to deduce return type from adding two @c matrix_cls
> Should we stick with \c?

@syclik I actually just did a grep for \c and am not seeing it used in the Stan library? I'm pretty sure `@c $1` is just shorthand for `\code{$1}`. Is it okay to leave these as is?

2019-07-25 07:42 UTC, rok-cesnovar commented on stan/math/opencl/partial_types.hpp
> + * Performs bitwise @c and to deduce return type from adding two @c matrix_cls
I think most of the Stan Math codebase uses <code></code>.

2019-07-25 08:08 UTC, SteveBronder commented on stan/math/opencl/partial_types.hpp
> + * Performs bitwise @c and to deduce return type from adding two @c matrix_cls
imo it feels like `<code></code>` makes the docs harder to read when reading the codebase

2019-07-25 08:08 UTC, merged

2019-08-01 07:05 UTC, syclik commented on stan/math/opencl/partial_types.hpp
> + * Performs bitwise @c and to deduce return type from adding two @c matrix_cls
Sorry for the late reply... it doesn't really matter as long as we're consistent.

I'd go with `\c` over `@c`, but that's just because the only `@` we use from doxygen is `@param`, `@tparam`, `@return`... we use `\` for things like `\f`, `\code`, and pretty much everything else. I don't know why... maybe we should switch everything to one or the other or have a rule for which we use when.

I think `<code></code>` seems more verbose than necessary and maybe we can swap all of that with `\c`.

2019-08-01 07:05 UTC, syclik commented on stan/math/opencl/partial_types.hpp
> + * Performs bitwise @c and to deduce return type from adding two @c matrix_cls
or... `\code`?