[WIP] Rework adj_jac_apply
bstatcomp/math pull request #18
Opened 2020-08-05 14:29 UTC by t4c1

Thanks for submitting a pull request! Please remove this text when submitting.

Start by filling in the Summary, Tests, and Side Effects sections of this pull request and then work through the handy checklist at the bottom. If anything significant is missing, the pull request may be closed until it's ready. The full guidebook on how pull requests are reviewed is here: [Code Review Guidelines](https://github.com/stan-dev/math/wiki/Developer-Doc#code-review-guidelines).

## Summary

Describe the contents of the pull request. The issue describes the problem that needs to be fixed, whereas the text here should help the reviewer figure out to what extent this pull request solves the issue.

Describe implementation details and any relevant information that would help the code reviewer understand this pull request. If there is anything special you need to draw someone's attention to, do it here. Link to any related pull requests or Discourse threads.

## Tests

Describe the new tests with the pull request.

For bug fixes there should be a new test that would fail if the patch weren't in place (so that the bug could be caught if it comes up again).

For new features there should be at least one test showing the expected behavior and one test that demonstrates error handling. Be aware the reviewer will very likely ask for more tests than this, but it's a start.

## Side Effects

Are there any side effects that we should be aware of?

## Release notes

Replace this text with a short note on what will change if this pull request is merged in which case this will be included in the release notes.

## Checklist

- [ ] Math issue #(issue number)

- [ ] Copyright holder: (fill in copyright holder information)

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [ ] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [ ] the code is written in idiomatic C++ and changes are documented in the doxygen

- [ ] the new changes are tested

2020-08-05 16:27 UTC, bbbales2 commented
That is waaay less code. In `adj_jac_apply` currently everything lives inside a functor because the functor is the object that keeps track of all the memory we allocate on the stack. All the `adj_jac_vari` stuff wraps around this to save references to the right `vari*` s.

In this solution the lambda copies in local variables which have allocated memory in the right places (and the copies are there so that the lambdas aren't using locals that go out of scope). These local variables track the appropriate `vari*` s.

At face value this looks like it would work so a few things:

1. I don't think `AD_stack_matrix` should necessarily copy all the vars. We only need the `vari*` s for the inputs. I suspect we could add enough types or template parameters to make this work.

2. One of the things `adj_jac_apply` does is make it so that one bit of code can work for any combination of autodiff/non-autodiff inputs. What does that look like here?

3. For some types of input, some computation is optional. [Here](https://gist.github.com/bbbales2/523db7848df48117dd39788815dfe1a2) is an example of an adj_jac_apply functor with optional computation. How does that fit in?

2020-08-05 17:11 UTC, t4c1 commented
1. Well var only has a single member - `vari*`. So it does not matter if we copy var or vari* . size is the same.
2. and 3. That is all left to the implementation of the function. We can handle optional computation and varied types the same way as we do in distributions.

2020-08-05 18:05 UTC, bbbales2 commented
> size is the same.

Good point lol.

> the same way as we do in distributions.

Here's the `Ax = b` solve with a couple inline comments/questions:

```cpp
inline Eigen::Matrix<var, Eigen::Dynamic, 1> solve(
    const Eigen::Matrix<T1, Eigen::Dynamic, Eigen::Dynamic>& A,
    const Eigen::Matrix<T2, Eigen::Dynamic, 1>& b) {
  check_square("solve", "A", A);
  check_size_match("solve", "Rows of A", A.rows(), "Rows of b", b.rows());
  
  // Save the input arguments
  // Sometimes we want to save the values if they aren't autodiff types and
  //  sometimes we don't. This isn't happening here, but I think AD_stack_matrix
  //  should get a `Save` boolean template parameter so it can be saved or not
  //  based on template logic
  AD_stack_matrix<Eigen::Matrix<T1, Eigen::Dynamic, Eigen::Dynamic>> A_stack = A;
  AD_stack_matrix<Eigen::Matrix<T2, Eigen::Dynamic, 1>> b_stack = b;
  
  auto A_llt = A.llt();
  // Save the output as a var
  AD_stack_matrix<Eigen::Matrix<stan::return_type_t<T1, T2>, Eigen::Dynamic, 1>> x = A_llt.solve(b);
  
  // Save a copy of the decomposition of A for later
  AD_stack_matrix<Eigen::MatrixXd> A_llt_stack;
  
  A_llt_stack.template triangularView<Eigen::Lower>() = A_llt.matrixL();
  A_llt_stack.template triangularView<Eigen::Upper>() = A_llt_matrix.transpose();
  
  adjac_apply([=]() mutable {
    // We gotta compute adjb if either inputs contain vars
    Eigen::Matrix<double, Eigen::Dynamic, 1> adjb = x.adj();
    
    A_llt_stack.template triangularView<Eigen::Lower>().solveInPlace(adjb);
    A_llt_stack.template triangularView<Eigen::Upper>().solveInPlace(adjb);
    
    // This seems cleaner
    //b_stack.adj() += adjb;
    
    // But this seems easier to implement as a no-op when A or b are not vars
    b_stack.accumulate_adj(adjb);
    
    // We only need to compute adjA in certain cases
    if(!is_constant<T1>::value) {
      A_stack.accumulate_adj(-adjb * x.transpose());
    }
  });
  
  return res;
}
```

@SteveBronder This seems better to me. Do you see problems?

2020-08-05 18:07 UTC, bbbales2 commented
We'd also need the `AD_stack` utility to do `std::vector` s, scalars, and such like `adj_arg` does.

2020-08-05 18:11 UTC, t4c1 commented
Actually i already made it in https://github.com/stan-dev/math/pull/1970. It is `std::vector<T, AD_allocator<T>>`.

2020-08-05 18:13 UTC, t4c1 commented
>// Sometimes we want to save the values if they aren't autodiff types and
  //  sometimes we don't. This isn't happening here, but I think AD_stack_matrix
  //  should get a `Save` boolean template parameter so it can be saved or not
  //  based on template logic

Can you give me an example where?

2020-08-05 18:16 UTC, bbbales2 commented
Multiplication (example code [here](https://github.com/stan-dev/math/blob/f1f32af911b15e3ca4f991b85f03caba9d93caf5/stan/math/rev/core/operator_multiplication.hpp#L305)).

If you have `C = A * B`, `adjA = adjC * B.transpose()`. So you need the values of B whether or not it is an autodiff type.

2020-08-05 19:22 UTC, SteveBronder commented
Huh, I like this! Much more straightforward. I think it's fine to expect users to know to use `value_of`. Got a few Qs

1. Can you show me `softmax` but for `var<Eigen>`? Looking at `AD_stack_matrix` I'm not sure how that would work, though the lambda in `adjac_apply` for `softmax` would def great
2. Instead of `AD_stack_matrix` how about just `stack_map`?
3. Can you run some quick perf tests versus the current impl? imo I think it will be faster but would like to sanity check it
4. (optional) If we know that Eigen matrices of var's are coming into `AD_stack_matrix`, and we frequently do `.adj()` and `.val()` on those during the reverse pass, do you think it's worth doing essentially the same thing as `var<Eigen>` and storing the `adj_` and `val_` here as separate values in `AD_stack_matrix`? 
5. Am I reading this right that a few pieces here are for efficiency where it could be shortened to

```cpp
  // forward pass
  AD_stack_matrix<Eigen::Matrix<var, Eigen::Dynamic, 1>> res = softmax(value_of(alpha));
  AD_stack_matrix<Eigen::Matrix<var, Eigen::Dynamic, 1>> alpha_ad_stack = alpha;
  // reverse pass
  adjac_apply([=]() mutable {
    alpha_ad_stack.adj() = -res.val() * res.adj().dot(res.val()) + res.val().cwiseProduct(res.adj());
  });
```

I think that's cool! though it's a little non-standard from our usual pattern. It's more of a callback pattern (which is what reverse mode does anyway). What would you and Ben think about renaming `adjac_apply` to `adjac_callback`? I think `adjac_callback` is more straightforward that it's adding a vari functor to our vari stack as a side effect that will be called in the reverse mode pass.

2020-08-05 19:22 UTC, SteveBronder commented
lol we can delete a lot of code with this that's awesome!

2020-08-05 19:30 UTC, bbbales2 commented
`reverse_callback` is fine with me, in the theme of the renames in the other refactor.

2020-08-05 20:05 UTC, SteveBronder commented
>>    // Sometimes we want to save the values if they aren't autodiff types and
>>    // sometimes we don't. This isn't happening here, but I think AD_stack_matrix
>>    // should get a Save boolean template parameter so it can be saved or not
>>    // based on template logic

> Can you give me an example where?

I think right here
```cpp
    // We gotta compute adjb if either inputs contain vars
    Eigen::Matrix<double, Eigen::Dynamic, 1> adjb = x.adj();
```

But the lambda can use the T1 and T2 template parmeters so we can use them when making the lambda

if (disjunction<is_var<T1>, is_var<T2>>::value) {
  // do stuff
}

And all the data there has already been allocated, since the lambda doesn't return anything we can just have specific parts in ifs and not worry about needing scope in those

2020-08-06 12:07 UTC, t4c1 commented
> Can you show me softmax but for var<Eigen>? Looking at AD_stack_matrix I'm not sure how that would work, though the lambda in adjac_apply for softmax would def work

I think the my current softmax code should just work. Just change types of input argument, res and function return type to var_value. We will have to do some template meta magic to only do copies if necessary.

> Instead of AD_stack_matrix how about just stack_map?

I prefere matrix to map as it behaves more like `Eigen::Matrix` than `Eigen::Map` in terms that it manages its own memory.

> Can you run some quick perf tests versus the current impl? imo I think it will be faster but would like to sanity check it

Will do.

> (optional) If we know that Eigen matrices of var's are coming into AD_stack_matrix, and we frequently do .adj() and .val() on those during the reverse pass, do you think it's worth doing essentially the same thing as var<Eigen> and storing the adj_ and val_ here as separate values in AD_stack_matrix?

Imo as soon as we need val or adj more than once it is worth making a copy. If we temaplate the same implementation for Matrix<var> and var_value<Matrix> we just have to use ref_type_t for those to do these copies only for Matrix<var> (i guess I have to do a version of ref that will put copies on AD stack). If we need something in both forward in revers pass than we put it on stack. If it is needed in just one pass we can just use "normal" non stack refs.

> Am I reading this right that a few pieces here are for efficiency where it could be shortened to

Yes.

> What would you and Ben think about renaming adjac_apply to adjac_callback?

I was thinking about renaming too. How about `reverse_pass_callback`?

> Multiplication (example code here).

I was hoping for an example that is already in this/develop branch, so that I can just do it as a demo without touching testing etc.

2020-08-06 12:23 UTC, t4c1 commented
Benchmark!

code:
```
#include <benchmark/benchmark.h>
#include <stan/math.hpp>
#include <iostream>

using namespace stan::math;
using namespace Eigen;
using namespace std;

static void softmax_bench(benchmark::State& state) {
  const int N = state.range(0);
  VectorXd alpha_val = VectorXd::Random(N);
  for (auto _ : state) {
    Matrix<var, -1, 1> alpha = alpha_val;
    var lp = sum(softmax(alpha));
    lp.grad();
    recover_memory();
  }
}

BENCHMARK(softmax_bench)->Args({200000});
BENCHMARK_MAIN();

```

Results for this branch:
```
-------------------------------------------------------------------
Benchmark                            Time           CPU Iterations
-------------------------------------------------------------------
softmax_bench/200000_mean     12170868 ns   11938477 ns         64
softmax_bench/200000_median   12144552 ns   11962891 ns         64
softmax_bench/200000_stddev      64138 ns     292290 ns         64
```
Result for develop:
```
-------------------------------------------------------------------
Benchmark                            Time           CPU Iterations
-------------------------------------------------------------------
softmax_bench/200000_mean     13932244 ns   13906250 ns         50
softmax_bench/200000_median   13935789 ns   13906250 ns         50
softmax_bench/200000_stddev      53063 ns     164702 ns         50
```

So this is a bit faster.

2020-08-06 17:13 UTC, SteveBronder commented
I ran that bench through some other sizes then ended up cutting into it a bit because I was surprised it wasn't getting more of a speedup. I ended up with [this](https://gist.github.com/SteveBronder/759cc32018caa90252d1daff0c41baf6) and the results are, extremely good

![image](https://user-images.githubusercontent.com/5857231/89561377-67ac0c80-d7e6-11ea-9286-3810eec1600e.png)


lol, it really shaves off all the overhead!


> I prefere matrix to map as it behaves more like Eigen::Matrix than Eigen::Map in terms that it manages its own memory.

I'm cool with `stack_matrix`

> Imo as soon as we need val or adj more than once it is worth making a copy.

Rad!

> I was thinking about renaming too. How about `reverse_pass_callback`?

I think that makes sense, @bbbales2 is there any reason we would want to specifically have `adj_jac` in the name?

> I was hoping for an example that is already in this/develop branch, so that I can just do it as a demo without touching testing etc. I don't need it to already use adj_jac_apply.

Sadly idt there is. `adj_jac` was only used in a few places in `rev`

2020-08-06 17:24 UTC, bbbales2 commented
> we would want to specifically have adj_jac in the name?

Nope, `reverse_pass_callback` or `reverse_callback` are fine with me.

> I was hoping for an example that is already in this/develop branch ... I don't need it to already use adj_jac_apply.

[This](https://github.com/stan-dev/math/blob/develop/stan/math/rev/fun/dot_product.hpp) would probably be easy enough, could replace a bunch of code, and has a `std::vector` interface.

There's a version that takes in `vari*` which is weird and if it's used somewhere I think I'd rather just remove it (since we can always use `Eigen::Map` types to do our math here).

2020-08-06 17:26 UTC, bbbales2 commented
> it really shaves off all the overhead!

Did you do anything differently in the implementation? Or is this a different benchmark?

2020-08-06 17:55 UTC, SteveBronder commented
> Did you do anything differently in the implementation? Or is this a different benchmark?

Same impl, the only thing I did is manual timing so we only capture the time of running `var lp = sum(softmax(alpha));` and the `lp.grad()`

2020-08-07 19:27 UTC, bbbales2 requested changes
This rules. @bob-carpenter have a look at `stan/math/rev/fun/softmax.hpp` in this pull. It's a slick new way to do reverse mode implementations (that @t4c1 came up with -- you can look at `stan/math/rev/fun/dot_product.hpp` to see how much it cleans up the older code).

This also seems like a model for specifying custom reverse mode autodiff that would be more suitable for the Stan language itself. Previously I was thinking of imitating `adj_jac_apply` but that would require the Stan language to have structs and such (which we don't have plans for currently). This would just require closures (which we do have plans for) and some autodiff-aware user-logic.

Like:

```stan
vector myfunc(real a, vector b) {
  // implementation of function
  ...
  reverse_mode_callback({
     if(is_autodiff(a)) {
       a.adj() += ...;
     }
     ...
  });

  return output;
}
```

I wonder how forward mode could interact with this. It would be cool to get rid of operands and partials entirely, but that can wait.

2020-08-07 19:27 UTC, bbbales2 commented on stan/math/rev/fun/dot_product.hpp
> +  var res(new vari(dot_product(v1_val, v2_val)));
If we use `return_type_t<T1, T2>` in this function all the vars go away.

2020-08-07 19:27 UTC, bbbales2 commented on stan/math/rev/fun/dot_product.hpp
> +
The saving logic for this function is based on the T1, T2 types.

If T1 is double and T2 is double, then we save nothing.

If T1 is var and T2 is double, then we save the vars for T1 and the doubles for T2.

If T1 is double and T2 is var, then we save the vars for T2 and the doubles for T1.

If T1 is var and T2 is var, then we save the vars for T1 and T2.

And that simplifies to:

If either of T1 or T2 are not doubles, save everything.

For memory efficiency I don't think v1_val and v1_ad_stack should be different variables is what I'm getting at.

2020-08-07 19:27 UTC, bbbales2 commented on stan/math/rev/fun/to_ad_stack.hpp
>    return {a.begin(), a.end()};
Because `std::vector` has an intializer list signature, won't this do the equivalent of:

```
AD_stack_t<std::vector<T>> out = {a.begin(), a.end()};
```

not

```
AD_stack_t<std::vector<T>> out(a.begin(), a.end());
```

2020-08-07 19:27 UTC, bbbales2 commented on stan/math/rev/fun/dot_product.hpp
> +      v1_ad_stack.adj() += res.adj() * v2_val;
This always compiles because even if T1 is a double, the hypothetical-but-unallocated `.adj()` member exists?

2020-08-07 19:27 UTC, bbbales2 commented on stan/math/rev/fun/softmax.hpp
> +  return res;
When this returns, it copy-constructs an `Eigen::Matrix<var, Eigen::Dynamic, 1>` from an `AD_stack_matrix<Eigen::Matrix<var, Eigen::Dynamic, 1>>`, right?

 And this will go away when all our functions accept general Eigen types (which I assume happens at the same time as the expression support is all there)?

2020-08-07 19:27 UTC, bbbales2 commented on stan/math/prim/fun/dot_product.hpp
> +inline auto dot_product(const std::vector<Scalar1, Alloc1> &v1,
Is this used anywhere? We aren't letting our weird `AD_stack` types leak out anywhere so do we need this yet (or maybe this is future-proofing)?

2020-08-07 19:32 UTC, rok-cesnovar commented
```stan
vector myfunc(real a, vector b) {
  // implementation of function
  ...
  reverse_mode_callback({
     if(is_autodiff(a)) {
       a.adj() += ...;
     }
     ...
  });

  return output;
}
```
Nice. 

Also this is all really cool. I warned you all Tadej knows his stuff :)

2020-08-07 19:44 UTC, syclik commented
That's really neat.

2020-08-07 22:14 UTC, SteveBronder reviewed
Quick lil' review

2020-08-07 22:14 UTC, SteveBronder commented on stan/math/rev/fun/dot_product.hpp
> +  }
@t4c1 @bbbales2 how would yinz feel about having this like

```cpp
  AD_stack_matrix<!is_constant<T2>::value, plain_type_t<T2>> v2_ad_stack(v2_col);
```

A bit of a mouthful but then we don't need the if's after. We could have a `negate<>` like

```cpp
template <typename B>
struct negate {
  static constexpr bool value{!B::value};
};
```

And within `AD_stack_matrix` check the `value`. Then at least it becomes

```cpp
  AD_stack_matrix<negate<is_constant<T2>>,  plain_type_t<T2>> v2_ad_stack(v2_col);
```

I'd also still prefer we use lowercase camel case like `ad_stack_matrix`. Though it's only for reverse mode so we could also call it `rev_stack_matrix`.

Also I'm guessing that by default we will want to store the memory here if the template type is not constant. So we could have `AD_stack_matrix`'s templates like

```cpp
template <typename T, bool B = !is_constant<T>::value>
```

Then this case simplifies down to

```cpp
  rev_stack_matrix<plain_type_t<T2>> v2_ad_stack(v2_col);
```

2020-08-07 22:14 UTC, SteveBronder commented on stan/math/rev/functor/reverse_pass_callback.hpp
> +  callback_vari(F&& rev_functor) : rev_functor_(rev_functor) {
```suggestion
  callback_vari(F&& rev_functor) : rev_functor_(std::forward<F>(rev_functor)) {
```

2020-08-07 22:14 UTC, SteveBronder commented on stan/math/rev/functor/reverse_pass_callback.hpp
> +  F rev_functor_;
If this inherits from vari_base then I think it needs an `init_dependent()`

2020-08-10 07:35 UTC, t4c1 commented on stan/math/rev/fun/to_ad_stack.hpp
>    return {a.begin(), a.end()};
This is tested here and it works as expected: https://github.com/stan-dev/math/blob/c42690e67e55f400a5e57a92a4ed91d1843975f9/test/unit/math/rev/fun/to_ad_stack_test.cpp#L22

2020-08-10 08:21 UTC, t4c1 commented on stan/math/rev/fun/dot_product.hpp
> +  var res(new vari(dot_product(v1_val, v2_val)));
What would be advantage of that? This can not be anything else, but var.

2020-08-10 08:27 UTC, t4c1 commented on stan/math/rev/fun/dot_product.hpp
> +
Here we can decide if we want to favor faster execution or lower memory usage. I went for faster execution. This is faster as accessing .val() on matrix/vector of vars is relatively slow. As we need the values twice, I decided to make a copy to speed it up. As one of these uses is in forward and one in reverse pass, this copy must be on the ad stack.

2020-08-10 08:27 UTC, t4c1 commented on stan/math/rev/fun/to_ad_stack.hpp
>    return {a.begin(), a.end()};
Also types don't match for the initializer list constructor.

2020-08-10 08:28 UTC, t4c1 commented on stan/math/rev/fun/dot_product.hpp
> +      v1_ad_stack.adj() += res.adj() * v2_val;
This always compiles as scalar in `v1_ad_stack` is always `var`. If not needed `v1_ad_stack` is empty.

2020-08-10 08:29 UTC, t4c1 commented on stan/math/rev/fun/softmax.hpp
> +  return res;
Right.

2020-08-10 08:33 UTC, t4c1 commented on stan/math/prim/fun/dot_product.hpp
> +inline auto dot_product(const std::vector<Scalar1, Alloc1> &v1,
We are using this. In rev `dot_product` if both inputs are std vectors of vars, their values are saved in arena and this is used to calculate the result of the forward pass.

2020-08-10 08:45 UTC, t4c1 commented on stan/math/rev/fun/dot_product.hpp
> +  }
Hmm, I need to think about this. It feels a bit restrictive, but it might also be fine. I will come back to this after I try to use this on var_value. 

> Also I'm guessing that by default we will want to store the memory here if the template type is not constant. So we could have AD_stack_matrix's templates like

This will not work. Sometimes we are also saving prim types.

2020-08-10 08:45 UTC, t4c1 commented on stan/math/rev/functor/reverse_pass_callback.hpp
> +  callback_vari(F&& rev_functor) : rev_functor_(rev_functor) {
fixed

2020-08-10 09:14 UTC, t4c1 commented on stan/math/rev/functor/reverse_pass_callback.hpp
> +  F rev_functor_;
fixed

2020-08-10 09:41 UTC, t4c1 commented on stan/math/rev/fun/dot_product.hpp
> +  }
> how would yinz feel about having this like

Templating a type with whether it is used or not seems a bit weird to me. This feels more like you want to template the constructor. Explicit specifications of constructor templates are not possible, but we can do this via a factory function.

Than this would look like:
```
auto v2_ad_stack = AD_stack_matrix<Eigen::Matrix<var, Eigen::Dynamic, 1>>::
                       construct_if<!is_constant<T2>::value>(v2_col);
```

> We could have a negate<> like

It is `negation` in c++17, so we should use that name if we decide to add that. Also I prefere `! ::value` to `negate< >` - less brackets means more readable code.

Also I am intentionally using `var` instead of  `plain_type_t<T2>` here. Otherwise calls to `.adj()` in rev pass would not compile.

2020-08-10 17:04 UTC, SteveBronder commented on stan/math/rev/fun/dot_product.hpp
> +  }
> This will not work. Sometimes we are also saving prim types.

Saving it based on whether it's a var or not would be the default, but users could override it. I think the use case for saving prim types is whenever another type is a `var` and we need the prim to perform the reverse mode. So for that it would look like

```cpp
// Saving T2 based on whether T1 is a var
AD_stack_matrix<Eigen::Matrix<var, Eigen::Dynamic, 1>, !is_constant<T1>::value> v2_ad_stack;
```

> Templating a type with whether it is used or not seems a bit weird to me. This feels more like you want to template the constructor. Explicit specifications of constructor templates are not possible, but we can do this via a factory function

What part of it seems odd (genuinely asking, we do use that in other part of stan like the error functions). 

```cpp
auto v2_ad_stack = AD_stack_matrix<Eigen::Matrix<var, Eigen::Dynamic, 1>>::
                       construct_if<!is_constant<T2>::value>(v2_col);
```

I think I get part of what your saying with this, but the above is sort of a mouthful. Would we have anything in the factory besides `constuct_if?` I'm not sure how I feel about that robust of syntax. Though if Ben also likes this then I'm fine with it.

> It is negation in c++17, so we should use that name if we decide to add that. Also I prefere ! ::value to negate< > - less brackets means more readable code.

Sure I'm cool with that.

2020-08-10 18:50 UTC, bbbales2 commented on stan/math/rev/fun/dot_product.hpp
> +  var res(new vari(dot_product(v1_val, v2_val)));
Fair I was thinking about what would happen if we tried to use this in prim like operands and partials for all the autodiff types. Can skip.

2020-08-10 19:59 UTC, bbbales2 commented on stan/math/rev/fun/dot_product.hpp
> +
This optimization would only matter if both things are filled with vars, otherwise saving everything is equivalent to the optimization.

I think the issue here is that with the varis, even if you're only touching the adjoints, you'll presumably load up the values with the cache line, so the values will be there.

I'd expect something like this might be competitive as well (since it minimizes memory movement):
```
reverse_pass_callback([=]() mutable {
  for(size_t i = 0; i < v1_arena.size(); ++i) {
    v1_arena.coeffRef(i).adj() += res.adj() * v2_arena.coeffRef(i).val();
    v2_arena.coeffRef(i).adj() += res.adj() * v1_arena.coeffRef(i).val();
  }
});
```

Anyway I don't really know how to think on memory bound stuff without benchmarks. I get tricked and sometimes things matter and sometimes they don't. What's here is fine. I wanted to talk about the optional memory saving interface.

2020-08-10 19:59 UTC, bbbales2 commented on stan/math/rev/fun/to_ad_stack.hpp
>    return {a.begin(), a.end()};
Yeah you're right had a play on godbolt and this is fine.

2020-08-10 20:07 UTC, bbbales2 commented on stan/math/rev/fun/dot_product.hpp
> +  }
> Templating a type with whether it is used or not seems a bit weird to me.

> Saving it based on whether it's a var or not would be the default, but users could override it.

I agree that as much as we use this templating optional-save stuff it is really annoying to read the code (I forget what the random True/False/template logic things mean).

But then when I think about writing this code I think about optionally saving stuff based on template types (https://github.com/bstatcomp/math/pull/18#discussion_r467193500).

`to_arena<SaveLogic>(variable)` seems fine to me, but the feature here is more important to me than the syntax. I think it'll always look a little awkward.

2020-08-11 06:29 UTC, t4c1 commented on stan/math/rev/fun/dot_product.hpp
> +  }
> What part of it seems odd

Templating the whole type with a template that just changes how (or if) the type is constructed.

> but the above is sort of a mouthful

Better a mouthful than too restricting or confusing interface.

> Would we have anything in the factory besides constuct_if?

I think there is a misunderstanding. `constuct_if` in this example is the factory function. Depending on the template it would either construct the matrix from its argument or default construct it.

>to_arena<SaveLogic>(variable) seems fine to me

Yeah, actually we already have `to_arena_if`. I can use it here as well.

2020-08-11 07:25 UTC, t4c1 commented on stan/math/rev/fun/dot_product.hpp
> +
> If either of T1 or T2 are not doubles, save everything.

> This optimization would only matter if both things are filled with vars

Nope. It matters as soon as one of the arguments contains vars.

> I think the issue here is that with the varis, even if you're only touching the adjoints, you'll presumably load up the values with the cache line, so the values will be there.

Both what you said and we are accessing each value/adjoint trough a pointer.

> I'd expect something like this might be competitive as well

Yep. I would like to make this a bit easier to use. Something like what I made in kernel generator (https://github.com/stan-dev/math/blob/988a44ac0960f73b05c1b91baa847c29e3822f43/stan/math/opencl/kernel_generator/multi_result_kernel.hpp#L211).

In this example what you are suggesting is good. But in general replacing Eigen expressions with a loop will not use vectorization (if my understanding of Eigen is correct this example is not vectorized anyway as the destination `.adj()` is not contiguous).

2020-08-11 19:05 UTC, SteveBronder commented on stan/math/rev/fun/dot_product.hpp
> +  }
Word I think what you are saying makes sense so I'm cool with the factory style

2020-08-11 19:51 UTC, t4c1 commented on stan/math/rev/fun/dot_product.hpp
> +  }
Just pointing out that what is now on git is not what I meant with factory (I'm fine with either option, as this way we are reusing a function we need anyway, but we do need to use some `forward_as` calls).

2020-08-11 21:23 UTC, seantalts commented on stan/math/rev/fun/columns_dot_product.hpp
> +    ret(j) = dot_product(v1.col(j), v2.col(j));
.coeffRef?

2020-08-12 06:29 UTC, t4c1 commented on stan/math/rev/fun/dot_product.hpp
> +  }
I forgot to push the code to github yesterday. Sorry if the previous comment did not make much sense.

2020-08-12 06:34 UTC, t4c1 commented on stan/math/rev/fun/columns_dot_product.hpp
> +    ret(j) = dot_product(v1.col(j), v2.col(j));
sure

2020-08-12 08:45 UTC, t4c1 commented
PRs can not be moved to another fork, so I opened a new one here: https://github.com/stan-dev/math/pull/2011

2020-08-12 08:45 UTC, closed without merging